name: Deploy dist

on: push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v5.0.0
            - name: Setup node
              uses:  actions/setup-node@v6.0.0
              with:
                node-version: 22
            - name: Print node version
              run: node -v
            - name: Cache dependencies
              uses: actions/cache@v4
              id: cache
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm install
            - name: Run tests
              run: npm run test
            - name: Compeleted job
              run: echo "Test job compeleted"
    build:
        needs:
            - test
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v5.0.0
            - name: Setup node
              uses:  actions/setup-node@v6.0.0
              with:
                  node-version: 22
            - name: Print node version
              run: node -v
            - name: Cache dependencies
              uses: actions/cache@v4
              id: cache
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm install
            - name: Build project
              run: npm run build
            - name: Compeleted job
              run: echo "Test job compeleted"
    deploy:
        needs:
            - build
        runs-on: ubuntu-latest
        steps:
            - name: Deploy dist
              run: echo "Deployment compeleted"