name: Deploy react to github actionbs

on:
    push:
        branches:
            - master
        paths-ignore:
            - README.md

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v5.0.0
            - name: Setup node and install dependencies
              uses: ./.github/actions/setupnode
              with:
                node-version: 20
            - name: Build project
              run: npm run build
            - name: Upload static files as artifact
              id: deployment
              uses: actions/upload-pages-artifact@v3
              with:
                name: github-pages
                path: dist
    deploy:
        needs:
            - build
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GH pages
              id: deployment
              uses: actions/deploy-pages@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}