name: Deploy dist

on:
    push:
        branches:
            - master
        paths-ignore:
            - README.md

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v5.0.0
            - name: Setup node and install dependencies
              uses: ./.github/actions/setupnode
              with:
                node-version: 20
            - name: Run tests
              run: npm run test
            - name: Compeleted job
              run: echo "Test job compeleted"
    build:
        needs:
            - test
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v5.0.0
            - name: Setup node and install dependencies
              uses: ./.github/actions/setupnode
              with:
                node-version: 20
            - name: Build project
              run: npm run build
            - name: Upload dist artifact
              uses: actions/upload-artifact@v4
              with:
                name: dist-files
                path: dist
    deploy:
        needs:
            - build
        runs-on: ubuntu-latest
        steps:
            - name: Download dist artifact
              uses: actions/download-artifact@v4
              with:
                name: dist-files
                path: dist
            - name: Deploy dist
              run: |
                ls dist
                echo "Deployment compeleted"